### 查询所有
GET {{host}}/admin/code/list?pageNum=1&pageSize=2&typeCode=gender&typeName=性别&itemCode=M&itemName=男

### 根据主键查询
GET {{host}}/admin/code/getById?codeId=e62d9c45ca47785380c0458740284a49

### 根据多个类型代码查询, 返回代码值List
GET {{host}}/admin/code/getByTypeCodes?typeCode=menuType&typeCode=deviceType

### 根据多个类型代码查询, 返回代码值Map
GET {{host}}/admin/code/getMapByTypeCodes?typeCode=menuType&typeCode=deviceType

### 新增代码
POST {{host}}/admin/code/add
Content-Type: application/x-www-form-urlencoded

sysCode=admin&typeCode=type1&typeName=类型1&itemCode=item1&itemName=条目1&itemSort=1

### 编辑
POST {{host}}/admin/code/edit
Content-Type: application/x-www-form-urlencoded

codeId=47663d074f8347ea03d4948daf012367sysCode=admin&typeCode=type1&typeName=类型1&itemCode=item1&itemName=条目1&itemSort=1

### 删除
POST {{host}}/admin/code/delete
Content-Type: application/x-www-form-urlencoded

codeId=47663d074f8347ea03d4948daf012367

### 启用
POST {{host}}/admin/code/enable
Content-Type: application/x-www-form-urlencoded

codeId=47663d074f8347ea03d4948daf012367

### 禁用
POST {{host}}/admin/code/disable
Content-Type: application/x-www-form-urlencoded

codeId=47663d074f8347ea03d4948daf012367

### 清空并重新插入所有代码-开发环境使用
POST {{host}}/admin/code/truncateThenInsertAll
Content-Type: application/json

[
    {"sysCode": "admin", "typeCode": "module"          , "typeName": "模块"           , "itemCode": "admin"   , "itemName": "系统管理"  , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "module"          , "typeName": "模块"           , "itemCode": "file"    , "itemName": "文件管理"  , "itemSort": 2}
  , {"sysCode": "admin", "typeCode": "module"          , "typeName": "模块"           , "itemCode": "message" , "itemName": "消息管理"  , "itemSort": 3}
  , {"sysCode": "admin", "typeCode": "module"          , "typeName": "模块"           , "itemCode": "activiti", "itemName": "工作流"    , "itemSort": 4}
  , {"sysCode": "admin", "typeCode": "enableFlag"      , "typeName": "启用状态"       ,  "itemCode": "1"       , "itemName": "启用"      , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "enableFlag"      , "typeName": "启用状态"       ,  "itemCode": "0"       , "itemName": "停用"      , "itemSort": 2}
  , {"sysCode": "admin", "typeCode": "deleteFlag"      , "typeName": "删除标志"       ,  "itemCode": "1"       , "itemName": "未删除"    , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "deleteFlag"      , "typeName": "删除标志"       ,  "itemCode": "0"       , "itemName": "已删除"    , "itemSort": 2}
  , {"sysCode": "admin", "typeCode": "gender"          , "typeName": "性别"           , "itemCode": "M"       , "itemName": "男"         , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "gender"          , "typeName": "性别"           , "itemCode": "F"       , "itemName": "女"         , "itemSort": 2}
  , {"sysCode": "admin", "typeCode": "dataPermType"    , "typeName": "数据权限类型"    , "itemCode": "P"       , "itemName": "个人"       , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "dataPermType"    , "typeName": "数据权限类型"    , "itemCode": "O"       , "itemName": "本部门"     , "itemSort": 2}
  , {"sysCode": "admin", "typeCode": "dataPermType"    , "typeName": "数据权限类型"    , "itemCode": "M"       , "itemName": "多部门"     , "itemSort": 3}
  , {"sysCode": "admin", "typeCode": "roleType"        , "typeName": "角色类型"        , "itemCode": "N"       , "itemName": "正常"      , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "roleType"        , "typeName": "角色类型"        , "itemCode": "P"       , "itemName": "职位"      , "itemSort": 2}
  , {"sysCode": "admin", "typeCode": "orgType"         , "typeName": "部门类型"        , "itemCode": "0"       , "itemName": "公司"      , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "orgType"         , "typeName": "部门类型"        , "itemCode": "1"       , "itemName": "一级部门"  , "itemSort": 2}
  , {"sysCode": "admin", "typeCode": "orgType"         , "typeName": "部门类型"        , "itemCode": "2"       , "itemName": "二级部门"  , "itemSort": 3}
  , {"sysCode": "admin", "typeCode": "menuType"        , "typeName": "菜单类型"        , "itemCode": "G"       , "itemName": "菜单组"     , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "menuType"        , "typeName": "菜单类型"        , "itemCode": "M"       , "itemName": "菜单"       , "itemSort": 2}
  , {"sysCode": "admin", "typeCode": "menuType"        , "typeName": "菜单类型"        , "itemCode": "B"       , "itemName": "按钮"       , "itemSort": 3}
  , {"sysCode": "admin", "typeCode": "deviceType"      , "typeName": "设备类型"        , "itemCode": "B"       , "itemName": "浏览器"     , "itemSort": 1}
  , {"sysCode": "admin", "typeCode": "deviceType"      , "typeName": "设备类型"        , "itemCode": "M"       , "itemName": "移动端"     , "itemSort": 2}
]

###

