### 查询
GET {{host}}/admin/role/list?pageNum=1&pageSize=5&roleCodeOrName=管理

### 新增
POST {{host}}/admin/role/add
Content-Type: application/x-www-form-urlencoded

roleCode=generalManager&roleName=总经理&roleType=P

### roleCode=admin&roleName=超级管理员&roleType=N
### roleCode=adminCommon&roleName=管理员&roleType=N
### roleCode=adminMenu&roleName=所有菜单管理员&roleType=N
### roleCode=adminData&roleName=数据权限管理员&roleType=N
### roleCode=adminActiviti&roleName=工作流管理员&roleType=N
### roleCode=visitor&roleName=游客&roleType=N
### roleCode=custManager&roleName=客户经理&roleType=P
### roleCode=riskManager&roleName=风控经理&roleType=P
### roleCode=lawManager&roleName=法务经理&roleType=P
### roleCode=generalManager&roleName=总经理&roleType=P

### 编辑
POST {{host}}/admin/role/edit
Content-Type: application/x-www-form-urlencoded

roleId=47663d074f8347ea03d4948daf012367&roleCode=admin&roleName=超级管理员&roleType=N&roleDesc=超级管理员角色,编辑修改测试

### 删除
POST {{host}}/admin/role/delete
Content-Type: application/x-www-form-urlencoded

roleId=47663d074f8347ea03d4948daf012367

### 启用
POST {{host}}/admin/role/enable
Content-Type: application/x-www-form-urlencoded

roleId=47663d074f8347ea03d4948daf012367

### 禁用
POST {{host}}/admin/role/disable
Content-Type: application/x-www-form-urlencoded

roleId=47663d074f8347ea03d4948daf012367

### 根据主键查询
GET {{host}}/admin/role/getById?roleId=21f1630a569f9d8daa359f3aa96709bf

############################################################
### 根据主键查询关联用户
GET {{host}}/admin/role/listUser?roleId=21f1630a569f9d8daa359f3aa96709bf

### 根据主键查询关联菜单
GET {{host}}/admin/role/listMenu?roleId=21f1630a569f9d8daa359f3aa96709bf

### 角色添加用户
POST {{host}}/admin/role/addUser
Content-Type: application/x-www-form-urlencoded

roleId=aaa&roleId=bbb&userId=xxx&userId=yyy

### 角色分配菜单
POST {{host}}/admin/role/assignMenu
Content-Type: application/x-www-form-urlencoded

roleId=aaa&menuId=xxx&menuId=yyy
###