### 获取生成器分类列表
GET {{host}}/getGenMap

### 多个生成器重新获取数据
POST {{host}}/getDataByGenMeta
Content-Type: application/json

{
  "generatorMetaList": [
    {
      "className": "com.hepengju.hekele.data.generator.gen200_number.IntegerGenerator",
      "min": 60,
      "max": 100,
      "columnKey": "ck0001"
    },
    {
      "className": "com.hepengju.hekele.data.generator.gen300_string.CodeGenerator",
      "code": "A,B,C,D,E",
      "columnKey": "ck0002"
    }
  ],
  "sampleSize": 2
}


### 下载定制化的样例数据表格
POST {{host}}/downloadByGenMeta
Content-Type: application/json

{
  "generatorMetaList": [
    {
      "className": "com.hepengju.hekele.data.generator.gen200_number.IntegerGenerator",
      "min": 60,
      "max": 100,
      "columnKey": "ck0001",
      "columnName": "分数"
    },
    {
      "className": "com.hepengju.hekele.data.generator.gen300_string.CodeGenerator",
      "code": "A,B,C,D,E",
      "columnKey": "ck0002",
      "columnName": "等级"
    }
  ],
  "sampleSize": 5,
  "fileFormat": "tsv",
  "tableName": "测试"
}

###