# \u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hekele?serverTimezone=Asia/Shanghai
    username: hekele
    password: hekele123

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql.hepengju.cn:3306/hekele