# 调试测试
#debug: true

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hekele?serverTimezone=Asia/Shanghai
    username: hekele
    password: hekele123

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql.hepengju.cn:3306/hekele